name: Test Reusable Workflow

on:
  workflow_dispatch:

jobs:
  test:
    uses: maitreyrbhatt/appsec-workflows/.github/workflows/veracode-test.yml@main
    with:
      message: "Reusable workflow is working!"
